### ISSUE TITLE
Stack Trace Appearing in Console for No Apparent Reason

### ISSUE THREAD

**Issue by john01dav** [nguyenquyhy/DiscordBridge#32]
The following stack trace appears in my server console seemingly randomly:
```[23:42:58] [WritingThread/WARN] [de.btobastian.javacord.utils.DiscordWebsocketAdapter]: Websocket error!
com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: Connection closed by remote host
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:436) [WritingThread.class:?]
        at com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:386) [WritingThread.class:?]
        at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:119) [WritingThread.class:?]
        at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:57) [WritingThread.class:?]
Caused by: java.net.SocketException: Connection closed by remote host
        at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1555) ~[?:1.8.0_111]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71) ~[?:1.8.0_111]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_111]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_111]
        at java.io.FilterOutputStream.flush(FilterOutputStream.java:140) ~[?:1.8.0_111]
        at com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:273) ~[WritingThread.class:?]
        at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:424) ~[WritingThread.class:?]
        ... 3 more
```
It does not seem to affect the functioning of the plugin.

**Comment by popatop15** [comment]
https://gyazo.com/1b7972e1578c01cbf6497b6c53009d2b

Same issue. Just a bunch of console spam, plugin works fine, however.

**Comment by Bonkozorus** [comment]
Same issue here.

**Comment by nguyenquyhy** [comment]
Please try the latest 2.3.0 version and let me know if you still get this error 😄 .
